/**
 * passphrase.ts — provisions the SQLCipher passphrase for the local
 * encrypted store (§5 "encrypted with SQLCipher-backed plugin").
 *
 * DECISION (2026-09-02, confirmed with the user; §5 requires encryption
 * at rest but never says where the key comes from, and §6 defines no
 * key-provisioning endpoint):
 *
 *   A cryptographically-random passphrase is generated ON THE DEVICE at
 *   first run and persisted app-privately. It is never derived from the
 *   user's password, and never fetched from the server.
 *
 * Why not server-issued: a brand-new install would then be unable to
 * capture ANYTHING until it had first reached the workstation, which
 * directly contradicts §2 Rule 2 ("offline capture is durable") and Rule
 * 7 ("mobile capture must continue while the local workstation is
 * unavailable"). Why not derived from the password: it is unavailable
 * offline after login, and a password change would orphan the database.
 *
 * KEYSTORE UPGRADE (2026-09-03): this originally used @capacitor/
 * preferences (plain Android SharedPreferences — app-private but NOT
 * hardware-backed). It now uses `@aparajita/capacitor-secure-storage`,
 * whose Android implementation encrypts with AES-GCM under a key
 * generated by the Android Keystore before writing to SharedPreferences
 * (confirmed against the plugin's own README, not assumed). This is
 * exactly the swap `localDatabase.ts`'s doc comment anticipated: only
 * this function changed, because `localDatabase.ts` only ever asks for a
 * `PassphraseProvider` and never cares how the secret is stored.
 *
 * Existing installs: a passphrase already written under the old
 * @capacitor/preferences key is read once, migrated into secure storage,
 * and the old plaintext copy is removed — an in-place install must not
 * be locked out of its own already-encrypted database. A fresh install
 * never touches the old storage at all.
 *
 * Consequence worth knowing: if this value is lost (app data cleared,
 * uninstall), the local database is unrecoverable. §2 Rule 2 already
 * places device loss/uninstall outside the application guarantee, and the
 * server is authoritative after reconciliation.
 *
 * NOT DEVICE-VERIFIED, stated plainly rather than assumed: same category
 * as the rest of this local-storage layer (see localDatabase.ts's own
 * note) — this compiles and type-checks against the plugin's Android
 * implementation but has never executed on a real device/emulator, since
 * none is available in this environment. Confirm on first real device run
 * that `SecureStorage.getItem`/`setItem` actually round-trip.
 */

import { Preferences } from '@capacitor/preferences';
import { SecureStorage } from '@aparajita/capacitor-secure-storage';

const PASSPHRASE_KEY = 'baranguard.dbPassphrase';
/** The pre-Keystore-upgrade key, kept only for the one-time migration read. */
const LEGACY_PREFERENCES_KEY = 'baranguard.dbPassphrase';

/** 32 random bytes, hex-encoded — 256 bits of entropy. */
function generatePassphrase(): string {
  const bytes = new Uint8Array(32);
  crypto.getRandomValues(bytes);
  return Array.from(bytes, (b) => b.toString(16).padStart(2, '0')).join('');
}

/**
 * Returns this install's database passphrase, creating and persisting one
 * on first call. Suitable to pass directly to
 * `configureLocalDatabase()`.
 */
export async function getOrCreatePassphrase(): Promise<string> {
  const existing = await SecureStorage.getItem(PASSPHRASE_KEY);
  if (existing) return existing;

  // One-time migration path: an install that ran before the Keystore
  // upgrade has its passphrase sitting in plain @capacitor/preferences.
  // Move it into secure storage rather than generating a SECOND
  // passphrase, which would orphan the already-encrypted database.
  const legacy = await Preferences.get({ key: LEGACY_PREFERENCES_KEY });
  if (legacy.value) {
    await SecureStorage.setItem(PASSPHRASE_KEY, legacy.value);
    await Preferences.remove({ key: LEGACY_PREFERENCES_KEY });
    return legacy.value;
  }

  const passphrase = generatePassphrase();
  await SecureStorage.setItem(PASSPHRASE_KEY, passphrase);
  return passphrase;
}
