/**
 * blotter-detail.js — W7 Electronic Blotter Detail (§9).
 *
 * "Roles: Secretary (full incl. raw), others per §7. Evidence access
 * follows the same ownership policy as the API. Finalized blotter data is
 * read-only until an explicit amendment workflow. A real status/timestamp
 * timeline (created_at, dispatched_at, arrived_at, redaction_approved_at,
 * finalized_at), never a scripted one."
 *
 * This screen is where the Secretary FINALIZES and AMENDS the blotter.
 * Those two endpoints existed and were verified before this page did, but
 * nothing in the app called them — an endpoint with no caller is not a
 * feature. This closes that.
 *
 * WHAT LIVES WHERE (§9 splits these deliberately, so don't merge them):
 *   - W7 (this screen): the blotter record — finalize, amend, timeline.
 *   - W8 (ai-review.js): the AI draft — redact, regenerate, approve,
 *     translate, and the Lupon packet.
 * A "Review AI redaction" link connects the two for the Secretary, since
 * the real workflow runs approve (W8) -> finalize (W7) -> packet (W8).
 *
 * The action panel is driven entirely by REAL server state — whether the
 * incident has an approved redaction, and whether a blotter record exists
 * and is finalized. It never guesses, and when an action is unavailable it
 * says which prerequisite is missing rather than hiding the control (§8).
 *
 * kebab-case filename per §4.
 */

import {
  getIncident,
  getBlotterForIncident,
  getIncidentEvidence,
  resolveIncident,
  finalizeBlotter,
  amendBlotter,
  generateLuponPacket,
  logout,
  ApiClientError,
} from '../api/apiClient.js';
import { AppShell } from '../components/AppShell.js';
import { PageHeader } from '../components/PageHeader.js';
import { icons } from '../components/icons.js';
import { showToast } from '../components/Toast.js';
import { confirmDialog } from '../components/ConfirmDialog.js';

const INCIDENT_TYPE_LABELS = {
  theft: 'Theft', physical_injury: 'Physical Injury', disturbance: 'Disturbance',
  domestic_dispute: 'Domestic Dispute', vandalism: 'Vandalism',
  traffic_incident: 'Traffic Incident', fire: 'Fire',
  medical_emergency: 'Medical Emergency', missing_person: 'Missing Person',
  animal_complaint: 'Animal Complaint', other: 'Other',
};

const STATUS_PILL_CLASS = {
  pending: 'status-pill--pending',
  dispatched: 'status-pill--info',
  resolved: 'status-pill--success',
};

/**
 * Opens an official printable Republic of the Philippines / Barangay Blotter Record Sheet modal.
 */
function openPrintModal(incident, blotter, evidence) {
  const overlay = document.createElement('div');
  overlay.className = 'modal-backdrop';

  const modal = document.createElement('div');
  modal.className = 'modal-card';
  modal.style.maxWidth = '780px';
  modal.style.width = '95%';

  const blotterDisplayId = blotter?.displayId || incident?.displayId || `BLT-2026-${String(incident.incidentId).padStart(3, '0')}`;
  const incidentDate = new Date(incident.createdAt).toLocaleDateString('en-US', {
    month: 'long', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit'
  });

  modal.innerHTML = `
    <div style="display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--color-border);padding-bottom:1rem;margin-bottom:1.25rem;">
      <div style="display:flex;align-items:center;gap:0.75rem;">
        <div style="width:2.25rem;height:2.25rem;border-radius:8px;background:var(--tint-info-bg);color:var(--color-info);display:flex;align-items:center;justify-content:center;">
          ${icons.printer(18)}
        </div>
        <div>
          <h3 style="margin:0;font-size:1.15rem;font-weight:700;color:var(--color-text-primary);">Blotter Excerpt</h3>
          <p style="margin:0;font-size:0.8rem;color:var(--color-text-secondary);">Working copy — the audited packet is generated by Lupon Packet</p>
        </div>
      </div>
      <button class="ghost" id="close-print-modal" style="padding:0.35rem 0.65rem;">✕</button>
    </div>

    <!-- Official Printable Sheet -->
    <div id="printable-blotter-sheet" style="background:#ffffff;color:#1e293b;padding:2rem;border-radius:8px;border:1px solid #cbd5e1;box-shadow:0 4px 12px rgba(0,0,0,0.15);font-family:'Segoe UI',Roboto,Helvetica,sans-serif;">
      <div style="text-align:center;border-bottom:2px solid #0f172a;padding-bottom:1rem;margin-bottom:1.5rem;">
        <p style="margin:0;font-size:0.8rem;text-transform:uppercase;letter-spacing:0.05em;color:#64748b;">Republic of the Philippines</p>
        <p style="margin:0;font-size:0.85rem;font-weight:600;color:#334155;">Province of Sorsogon · Municipality of Pilar</p>
        <h2 style="margin:0.25rem 0 0 0;font-size:1.35rem;font-weight:800;color:#0f172a;letter-spacing:0.02em;">OFFICE OF THE LUPONG TAGAPAMAYAPA</h2>
        <p style="margin:0.25rem 0 0 0;font-size:0.95rem;font-weight:700;color:#2563eb;text-transform:uppercase;">EXTRACT COPY OF BARANGAY ELECTRONIC BLOTTER</p>
      </div>

      <div style="display:flex;justify-content:space-between;align-items:center;background:#f8fafc;border:1px solid #e2e8f0;padding:0.75rem 1rem;border-radius:6px;margin-bottom:1.25rem;">
        <div>
          <span style="font-size:0.75rem;color:#64748b;font-weight:600;text-transform:uppercase;">BLOTTER ENTRY NO.</span>
          <p style="margin:0;font-size:1.05rem;font-weight:800;color:#0f172a;font-family:monospace;">${blotterDisplayId}</p>
        </div>
        <div style="text-align:right;">
          <span style="font-size:0.75rem;color:#64748b;font-weight:600;text-transform:uppercase;">DATE & TIME LOGGED</span>
          <p style="margin:0;font-size:0.9rem;font-weight:600;color:#334155;">${incidentDate}</p>
        </div>
      </div>

      <div style="display:grid;grid-template-columns:1fr 1fr;gap:1rem;margin-bottom:1.25rem;">
        <div style="padding:0.75rem;border:1px solid #e2e8f0;border-radius:6px;">
          <span style="font-size:0.75rem;font-weight:700;color:#2563eb;text-transform:uppercase;">COMPLAINANT</span>
          <p style="margin:0.25rem 0 0 0;font-size:0.95rem;font-weight:600;color:#0f172a;">${blotter?.complainantName || incident.complainantName || 'Walk-in Complainant / Confidential'}</p>
          <p style="margin:0.15rem 0 0 0;font-size:0.8rem;color:#64748b;">Contact: ${blotter?.complainantContactNumber || incident.complainantContactNumber || 'Not recorded'}</p>
        </div>
        <div style="padding:0.75rem;border:1px solid #e2e8f0;border-radius:6px;">
          <span style="font-size:0.75rem;font-weight:700;color:#d97706;text-transform:uppercase;">RESPONDENT</span>
          <p style="margin:0.25rem 0 0 0;font-size:0.95rem;font-weight:600;color:#0f172a;">${blotter?.respondentName || incident.respondentName || 'Unspecified / Under Inquiry'}</p>
          <p style="margin:0.15rem 0 0 0;font-size:0.8rem;color:#64748b;">Type: ${INCIDENT_TYPE_LABELS[incident.incidentType] || incident.incidentType}</p>
        </div>
      </div>

      <div style="margin-bottom:1.25rem;">
        <span style="font-size:0.75rem;font-weight:700;color:#475569;text-transform:uppercase;">INCIDENT LOCATION</span>
        <p style="margin:0.25rem 0 0 0;font-size:0.88rem;color:#1e293b;background:#f8fafc;padding:0.5rem 0.75rem;border-radius:4px;border:1px solid #e2e8f0;">
          ${incident.locationDescription || (incident.latitude != null ? `${incident.latitude.toFixed(5)}, ${incident.longitude.toFixed(5)}` : 'Barangay Jurisdiction')}
        </p>
      </div>

      <div style="margin-bottom:1.25rem;">
        <span style="font-size:0.75rem;font-weight:700;color:#475569;text-transform:uppercase;">OFFICIAL STATEMENT & SUMMARY</span>
        <div style="margin-top:0.35rem;padding:0.85rem;background:#f8fafc;border-left:3px solid #2563eb;border-radius:0 4px 4px 0;font-size:0.88rem;line-height:1.6;color:#1e293b;white-space:pre-wrap;">
          ${blotter?.narrativeSummary || incident.redactedNarrative || incident.rawNarrative || 'No official summary provided.'}
        </div>
      </div>

      <div style="margin-top:2.5rem;display:flex;justify-content:space-between;padding-top:1.5rem;border-top:1px dashed #94a3b8;">
        <div style="text-align:center;width:40%;">
          <div style="border-bottom:1px solid #0f172a;margin-bottom:0.35rem;height:1.5rem;"></div>
          <p style="margin:0;font-size:0.85rem;font-weight:700;color:#0f172a;">RECORDING DESK OFFICER</p>
          <p style="margin:0;font-size:0.75rem;color:#64748b;">Barangay Secretary / Tanod on Duty</p>
        </div>
        <div style="text-align:center;width:40%;">
          <div style="border-bottom:1px solid #0f172a;margin-bottom:0.35rem;height:1.5rem;"></div>
          <p style="margin:0;font-size:0.85rem;font-weight:700;color:#0f172a;">ATTESTED & CERTIFIED</p>
          <p style="margin:0;font-size:0.75rem;color:#64748b;">Punong Barangay / Lupon Chairman</p>
        </div>
      </div>

      <!-- A browser print produces no audit row. The audited artefact is the
           server-generated Lupon packet (GET /incidents/:id/lupon-packet),
           so the printed page has to say what it is. -->
      <p style="margin:1.5rem 0 0 0;padding-top:0.75rem;border-top:1px solid #e2e8f0;font-size:0.7rem;color:#64748b;text-align:center;">
        Unaudited working copy printed from the Baranguard console. The official certified document for Lupon proceedings is the system-generated Lupon Packet.
      </p>
    </div>

    <div style="display:flex;justify-content:flex-end;gap:0.75rem;margin-top:1.25rem;border-top:1px solid var(--color-border);padding-top:1rem;">
      <button class="ghost" id="cancel-print-btn">Close</button>
      <button class="primary" id="do-print-btn" style="display:inline-flex;align-items:center;gap:0.4rem;">
        ${icons.printer(16)} Print working copy
      </button>
    </div>
  `;

  overlay.appendChild(modal);
  document.body.appendChild(overlay);

  const close = () => overlay.remove();
  modal.querySelector('#close-print-modal').addEventListener('click', close);
  modal.querySelector('#cancel-print-btn').addEventListener('click', close);
  modal.querySelector('#do-print-btn').addEventListener('click', () => {
    window.print();
  });
  overlay.addEventListener('click', (e) => {
    if (e.target === overlay) close();
  });
}

/**
 * @param {HTMLElement} root
 * @param {{fullName:string, role:string}} user
 * @param {() => void} onLoggedOut
 * @param {(page: string, param?: any) => void} navigate
 * @param {number} incidentId
 */
export function renderBlotterDetailPage(root, user, onLoggedOut, navigate, incidentId) {
  root.innerHTML = '';

  const isSecretary = user.role === 'secretary';

  const shell = AppShell(user, 'blotter', navigate, async () => {
    shell.logoutButton.disabled = true;
    await logout();
    onLoggedOut();
  });
  const { header, content } = shell;
  root.appendChild(shell.el);

  const pageHeader = PageHeader({
    title: `Blotter Entry — Incident #${incidentId}`,
    subtitle: 'Incident record, timeline, and blotter finalization',
    icon: icons.fileText,
  });
  header.appendChild(pageHeader.el);

  const backButton = document.createElement('button');
  backButton.className = 'ghost';
  backButton.textContent = '← Back to Blotter';
  backButton.addEventListener('click', () => navigate('blotter'));
  pageHeader.actions.appendChild(backButton);

  if (isSecretary) {
    const reviewButton = document.createElement('button');
    reviewButton.className = 'ghost';
    reviewButton.textContent = 'Review AI redaction';
    reviewButton.addEventListener('click', () => navigate('ai-review', incidentId));
    pageHeader.actions.appendChild(reviewButton);
  }

  let incident = null;
  let blotter = null;
  let evidence = [];

  load();

  async function load() {
    renderLoading();
    try {
      // The blotter legitimately may not exist yet (404 -> null); the
      // incident must, so its failure is a real error.
      [incident, blotter] = await Promise.all([
        getIncident(incidentId),
        getBlotterForIncident(incidentId),
      ]);
      // Evidence is enrichment — a failure degrades that one panel rather
      // than blanking a record the Secretary may need to act on. The
      // timeline's dispatch stages come from getIncident() above, NOT from
      // GET /dispatch, which a Secretary may not call at all (403).
      evidence = await getIncidentEvidence(incidentId).catch(() => []);
      render();
    } catch (err) {
      renderError(err instanceof ApiClientError ? err.message : 'Something went wrong loading this entry.');
    }
  }

  // --- States (§8: Loading / Empty / Error / Populated) ---

  function renderLoading() {
    content.innerHTML = '';
    const wrap = document.createElement('div');
    wrap.className = 'stack';
    wrap.setAttribute('role', 'status');
    wrap.setAttribute('aria-label', 'Loading blotter entry');
    for (let i = 0; i < 3; i++) {
      const skeleton = document.createElement('div');
      skeleton.className = 'skeleton skeleton--block';
      wrap.appendChild(skeleton);
    }
    content.appendChild(wrap);
  }

  function renderError(message) {
    content.innerHTML = '';
    const block = document.createElement('div');
    block.className = 'card state-block state-block--error';
    block.setAttribute('role', 'alert');
    const text = document.createElement('p');
    text.textContent = message;
    const retry = document.createElement('button');
    retry.className = 'primary';
    retry.textContent = 'Try again';
    retry.addEventListener('click', load);
    block.append(text, retry);
    content.appendChild(block);
  }

  /**
   * Two columns rather than six full-width cards stacked down the page,
   * which left the record itself narrow and the timeline stranded below
   * the fold. `.split-panel` is the existing utility for exactly this and
   * already collapses to one column at 1024px.
   *
   * Left is the record and the work done on it; right is context —
   * when things happened, and the Admin action that isn't part of the
   * Secretary's blotter workflow.
   */
  /**
   * Two columns rather than six full-width cards stacked down the page.
   * Left is the record and work done on it; right is context and audit trail.
   */
  function render() {
    content.innerHTML = '';

    const blotterDisplayId = blotter?.displayId || incident?.displayId || `BLT-2026-${String(incidentId).padStart(3, '0')}`;

    // Update Page Header Title & Subtitle
    const titleBlock = pageHeader.el.querySelector('.page-header__title');
    if (titleBlock) {
      titleBlock.innerHTML = `<span class="page-header__icon" aria-hidden="true">${icons.fileText(22)}</span> Blotter Entry — ${blotterDisplayId}`;
    }
    const subtitleBlock = pageHeader.el.querySelector('.page-header__subtitle');
    if (subtitleBlock) {
      subtitleBlock.textContent = 'Official Barangay Blotter Ledger · Katarungang Pambarangay §394';
    }

    // Refresh Action Buttons in Page Header
    pageHeader.actions.innerHTML = '';
    const actionsGroup = document.createElement('div');
    actionsGroup.className = 'blotter-detail-header-actions';

    const backButton = document.createElement('button');
    backButton.className = 'ghost';
    backButton.textContent = '← Back to Blotter';
    backButton.addEventListener('click', () => navigate('blotter'));
    actionsGroup.appendChild(backButton);

    const printButton = document.createElement('button');
    printButton.className = 'ghost';
    printButton.innerHTML = `${icons.printer(16)} Print Excerpt`;
    printButton.title = 'Print an unaudited working copy. The official, audited document is the Lupon Packet.';
    printButton.addEventListener('click', () => openPrintModal(incident, blotter, evidence));
    actionsGroup.appendChild(printButton);


    if (isSecretary) {
      const reviewButton = document.createElement('button');
      reviewButton.className = 'ghost';
      reviewButton.textContent = 'Review AI redaction';
      reviewButton.addEventListener('click', () => navigate('ai-review', incidentId));
      actionsGroup.appendChild(reviewButton);

      if (blotter?.finalizedAt) {
        const luponPacketBtn = document.createElement('button');
        luponPacketBtn.className = 'ghost';
        luponPacketBtn.innerHTML = `${icons.fileText(16)} Lupon Packet`;
        luponPacketBtn.title = 'Generate official Katarungang Pambarangay Lupon conciliation dossier';
        luponPacketBtn.addEventListener('click', async () => {
          luponPacketBtn.disabled = true;
          luponPacketBtn.textContent = 'Generating…';
          try {
            const res = await generateLuponPacket(incidentId);
            showToast('Lupon conciliation packet ready.', { variant: 'success' });
            if (res?.fileUrl) window.open(res.fileUrl, '_blank');
          } catch (err) {
            showToast(err instanceof ApiClientError ? err.message : 'Could not generate Lupon packet.', { variant: 'error' });
          } finally {
            luponPacketBtn.disabled = false;
            luponPacketBtn.innerHTML = `${icons.fileText(16)} Lupon Packet`;
          }
        });
        actionsGroup.appendChild(luponPacketBtn);
      }
    }

    pageHeader.actions.appendChild(actionsGroup);

    const layout = document.createElement('div');
    layout.className = 'split-panel';

    const main = document.createElement('div');
    main.className = 'blotter-detail__main';
    const aside = document.createElement('div');
    aside.className = 'blotter-detail__aside';

    // 1. Unified Case Dossier (Incident Type, Badges, Involved Parties, and 2x2 Meta)
    main.appendChild(buildDossierCard());

    // 2. Official Blotter Record (The core statutory record, placed prominently)
    if (isSecretary) {
      main.appendChild(buildBlotterPanel());
    } else if (blotter) {
      main.appendChild(buildReadOnlyBlotter());
    }

    // 3. Approved Redacted Narrative (RA 10173 compliant)
    main.appendChild(buildNarrative());

    // 4. Digital Evidence & Chain of Custody (Slim banner if empty)
    main.appendChild(buildEvidence());

    // Aside Column: Resolution Status Card first, then Stepped Timeline, then Legal Guide
    if (incident.status === 'resolved') {
      aside.appendChild(buildResolvedStatusCard());
    } else if (user.role === 'admin') {
      aside.appendChild(buildAdminResolvePanel());
    }
    aside.appendChild(buildTimeline());
    aside.appendChild(buildLegalGuide());

    layout.append(main, aside);
    content.appendChild(layout);
  }

  /**
   * Unified Case Dossier: Combines Incident Type, Badges, Involved Parties,
   * and Incident Particulars into a clear, spacious tiered layout with zero truncation.
   */
  function buildDossierCard() {
    const card = document.createElement('div');
    card.className = 'card case-hero';

    const blotterDisplayId = blotter?.displayId || incident?.displayId || `BLT-2026-${String(incident.incidentId).padStart(3, '0')}`;

    // Header Row: Type + Icon + Badges
    const headerRow = document.createElement('div');
    headerRow.className = 'case-hero__header';

    const titleGroup = document.createElement('div');
    titleGroup.className = 'case-hero__title-group';

    const iconWrap = document.createElement('div');
    iconWrap.className = 'case-hero__icon';
    iconWrap.innerHTML = icons.fileText(22);

    const title = document.createElement('h3');
    title.className = 'case-hero__title';
    title.textContent = INCIDENT_TYPE_LABELS[incident.incidentType] || incident.incidentType;

    titleGroup.append(iconWrap, title);

    const badges = document.createElement('div');
    badges.className = 'case-hero__badges';

    const idBadge = document.createElement('span');
    idBadge.className = 'blotter-id-badge';
    idBadge.innerHTML = `${icons.fileText(14)} ${blotterDisplayId}`;
    idBadge.title = 'Statutory Blotter Reference ID';

    const incidentBadge = document.createElement('span');
    incidentBadge.className = 'blotter-id-badge blotter-id-badge--incident';
    incidentBadge.innerHTML = `#${incident.incidentId}`;
    incidentBadge.title = `Incident System ID #${incident.incidentId}`;

    const statusPill = document.createElement('span');
    statusPill.className = `status-pill ${STATUS_PILL_CLASS[incident.status] || 'status-pill--neutral'}`;
    statusPill.textContent = `INCIDENT: ${(incident.status || 'unknown').toUpperCase()}`;

    const badgesToAppend = [idBadge, incidentBadge, statusPill];

    if (blotter?.caseStatus) {
      badgesToAppend.push(buildCaseStatusPill(blotter.caseStatus));
    }

    const priorityPill = document.createElement('span');
    priorityPill.className = `status-pill ${incident.priority === 'urgent' ? 'status-pill--pending' : 'status-pill--neutral'}`;
    priorityPill.textContent = `PRIORITY: ${incident.priority.toUpperCase()}`;
    badgesToAppend.push(priorityPill);

    badges.append(...badgesToAppend);
    headerRow.append(titleGroup, badges);
    card.appendChild(headerRow);

    // Dossier Body
    const dossierBody = document.createElement('div');
    dossierBody.className = 'dossier-body';

    // 1. Involved Parties (KP Law) - Full width 2-column grid
    const partiesSection = document.createElement('div');
    partiesSection.className = 'dossier-section';
    partiesSection.innerHTML = `<div class="dossier-section-title">${icons.users(14)} Involved Parties (Katarungang Pambarangay · RA 7160)</div>`;

    const partiesGrid = document.createElement('div');
    partiesGrid.className = 'parties-grid';

    const compCard = document.createElement('div');
    compCard.className = 'party-card';
    const compName = incident.complainantName || blotter?.complainantName || 'Walk-in Complainant / Confidential';
    const compContact = incident.complainantContactNumber || blotter?.complainantContactNumber || 'No contact number provided';
    compCard.innerHTML = `
      <div class="party-card__role">
        <span class="party-card__tag party-card__tag--complainant">Complainant</span>
        <span class="party-card__hint">Initiator / Reporting Party</span>
      </div>
      <div class="party-card__name">${compName}</div>
      <div class="party-card__contact">
        ${icons.phone(13)}
        <span>${compContact}</span>
      </div>
    `;

    const respCard = document.createElement('div');
    respCard.className = 'party-card';
    const respName = incident.respondentName || blotter?.respondentName || 'Unspecified / Under Investigation';
    respCard.innerHTML = `
      <div class="party-card__role">
        <span class="party-card__tag party-card__tag--respondent">Respondent</span>
        <span class="party-card__hint">Subject of Inquiry / Dispute</span>
      </div>
      <div class="party-card__name">${respName}</div>
      <div class="party-card__contact">
        ${icons.shield(13)}
        <span>Barangay inquiry & conciliation subject</span>
      </div>
    `;

    partiesGrid.append(compCard, respCard);
    partiesSection.appendChild(partiesGrid);

    // 2. Incident Particulars - Full-width 4-tile responsive grid
    const metaSection = document.createElement('div');
    metaSection.className = 'dossier-section';
    metaSection.innerHTML = `<div class="dossier-section-title">${icons.fileText(14)} Incident Particulars & Filing Record</div>`;

    const metaGrid = document.createElement('div');
    metaGrid.className = 'meta-grid-4col';

    // Location
    const locTile = document.createElement('div');
    locTile.className = 'meta-tile';
    const locCoords = incident.latitude != null && incident.longitude != null
      ? `${incident.latitude.toFixed(5)}, ${incident.longitude.toFixed(5)}`
      : 'Barangay Center';
    const locDesc = incident.locationDescription ? `${incident.locationDescription} (${locCoords})` : locCoords;
    locTile.innerHTML = `
      <div class="meta-tile__icon">${icons.mapPin(16)}</div>
      <div class="meta-tile__content">
        <span class="meta-tile__label">Location / Scene</span>
        <span class="meta-tile__value" title="${locDesc}">${locDesc}</span>
      </div>
    `;

    // Date Filed
    const dateTile = document.createElement('div');
    dateTile.className = 'meta-tile';
    const filedDate = new Date(incident.createdAt).toLocaleDateString('en-US', {
      month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit'
    });
    dateTile.innerHTML = `
      <div class="meta-tile__icon">${icons.clock(16)}</div>
      <div class="meta-tile__content">
        <span class="meta-tile__label">Date & Time Filed</span>
        <span class="meta-tile__value">${filedDate}</span>
      </div>
    `;

    // Channel
    const channelTile = document.createElement('div');
    channelTile.className = 'meta-tile';
    const channelLabel = incident.source === 'app' ? '📱 Mobile App' : incident.source === 'walkin' ? '🚶 Walk-in Desk' : '📞 Hotline Call';
    channelTile.innerHTML = `
      <div class="meta-tile__icon">${icons.phone(16)}</div>
      <div class="meta-tile__content">
        <span class="meta-tile__label">Reporting Channel</span>
        <span class="meta-tile__value">${channelLabel}</span>
      </div>
    `;

    // Officer
    const officerTile = document.createElement('div');
    officerTile.className = 'meta-tile';
    const officerName = incident.officerName || 'Barangay Desk Secretary';
    officerTile.innerHTML = `
      <div class="meta-tile__icon">${icons.users(16)}</div>
      <div class="meta-tile__content">
        <span class="meta-tile__label">Recording Officer</span>
        <span class="meta-tile__value">${officerName}</span>
      </div>
    `;

    metaGrid.append(locTile, dateTile, channelTile, officerTile);
    metaSection.appendChild(metaGrid);

    dossierBody.append(partiesSection, metaSection);
    card.appendChild(dossierBody);

    return card;
  }

  function buildNarrative() {
    const card = document.createElement('div');
    card.className = 'card doc-card';

    const header = document.createElement('div');
    header.className = 'doc-card__header';

    const titleGroup = document.createElement('div');
    titleGroup.className = 'doc-card__title-group';
    const heading = document.createElement('h3');
    heading.className = 'doc-card__title';
    heading.textContent = incident.redactedNarrative ? 'Approved Redacted Narrative' : 'Incident Narrative';
    titleGroup.appendChild(heading);

    const actions = document.createElement('div');
    actions.className = 'doc-card__actions';

    let isViewingRaw = false;

    if (incident.redactedNarrative) {
      const privacyBadge = document.createElement('span');
      privacyBadge.className = 'doc-privacy-badge';
      privacyBadge.title = 'A Secretary approved this redaction. This is a record of that approval, not a certification of statutory compliance.';
      privacyBadge.innerHTML = `${icons.shield(12)} Redaction approved`;
      actions.appendChild(privacyBadge);
    }

    let body = null;
    let secretaryNotice = null;

    if (isSecretary && incident.rawNarrative && incident.redactedNarrative) {
      const toggleBtn = document.createElement('button');
      toggleBtn.className = 'btn-copy';
      toggleBtn.innerHTML = `${icons.eye(14)} View Raw Intake`;
      toggleBtn.title = 'Toggle between public approved redacted narrative and original intake record (Secretary Privilege)';
      toggleBtn.addEventListener('click', () => {
        isViewingRaw = !isViewingRaw;
        if (isViewingRaw) {
          heading.textContent = 'Original Unredacted Intake Record';
          body.textContent = incident.rawNarrative;
          toggleBtn.innerHTML = `${icons.shield(14)} View Redacted`;
          secretaryNotice.style.display = 'block';
        } else {
          heading.textContent = 'Approved Redacted Narrative';
          body.textContent = incident.redactedNarrative;
          toggleBtn.innerHTML = `${icons.eye(14)} View Raw Intake`;
          secretaryNotice.style.display = 'none';
        }
      });
      actions.appendChild(toggleBtn);
    }

    const narrativeText = incident.redactedNarrative || (isSecretary ? incident.rawNarrative : null) || 'No narrative recorded yet.';

    const copyBtn = document.createElement('button');
    copyBtn.className = 'btn-copy';
    copyBtn.innerHTML = `${icons.fileText(14)} Copy Narrative`;
    copyBtn.addEventListener('click', () => {
      const currentText = body ? body.textContent : narrativeText;
      navigator.clipboard.writeText(currentText);
      showToast('Narrative copied to clipboard.', { variant: 'success' });
    });
    actions.appendChild(copyBtn);

    header.append(titleGroup, actions);
    card.appendChild(header);

    body = document.createElement('div');
    body.className = 'doc-blockquote';
    body.textContent = narrativeText;
    card.appendChild(body);

    secretaryNotice = document.createElement('p');
    secretaryNotice.className = 'note';
    secretaryNotice.style.marginTop = '0.5rem';
    secretaryNotice.style.display = 'none';
    secretaryNotice.style.color = 'var(--color-warning)';
    secretaryNotice.textContent = '🔒 Viewing original intake record with unredacted details under RA 7160 §394 statutory records privilege.';
    card.appendChild(secretaryNotice);

    if (!incident.redactedNarrative && isSecretary && incident.rawNarrative) {
      const warn = document.createElement('p');
      warn.className = 'note';
      warn.style.marginTop = '0.5rem';
      warn.textContent = 'This is the original unredacted narrative — no redaction has been approved yet.';
      card.appendChild(warn);
    }

    return card;
  }

  function buildEvidence() {
    if (evidence.length === 0) {
      const bar = document.createElement('div');
      bar.className = 'evidence-bar--empty';
      bar.innerHTML = `
        <div class="evidence-bar--empty__left">
          <span style="color:var(--color-text-secondary);display:flex;align-items:center;">${icons.shield(16)}</span>
          <span><strong>Digital Evidence:</strong> No attachments recorded for this entry. Chain of custody is intact.</span>
        </div>
        <span style="font-size:0.75rem;color:var(--color-text-secondary);">Statutory Audit Retention</span>
      `;
      return bar;
    }

    const card = document.createElement('div');
    card.className = 'card';

    const heading = document.createElement('h3');
    heading.textContent = `Digital Evidence & Chain of Custody (${evidence.length})`;
    card.appendChild(heading);

    const list = document.createElement('div');
    list.className = 'stack';
    list.style.gap = '0.5rem';
    for (const item of evidence) {
      const row = document.createElement('div');
      row.className = 'evidence-item';

      const left = document.createElement('div');
      left.className = 'evidence-item__left';
      const icon = document.createElement('div');
      icon.className = 'evidence-item__icon';
      icon.innerHTML = item.type === 'voice' ? icons.radio(18) : icons.fileText(18);

      const title = document.createElement('span');
      title.className = 'evidence-item__title';
      title.textContent = `${item.type === 'voice' ? 'Voice note' : 'Photo'} — ${item.originalFilename}`;
      left.append(icon, title);

      const meta = document.createElement('span');
      meta.className = 'evidence-item__meta';
      const kb = Math.max(1, Math.round(item.byteSize / 1024));
      meta.textContent = `${kb} KB · ${new Date(item.uploadedAt).toLocaleString()}`;

      row.append(left, meta);
      list.appendChild(row);
    }
    card.appendChild(list);

    const note = document.createElement('p');
    note.className = 'note';
    note.style.marginTop = '0.75rem';
    note.textContent = 'Evidence files are stored outside the web root and protected under Barangay chain-of-custody policies.';
    card.appendChild(note);

    return card;
  }

  function buildTimeline() {
    const card = document.createElement('div');
    card.className = 'card';

    const headerRow = document.createElement('div');
    headerRow.style.display = 'flex';
    headerRow.style.alignItems = 'center';
    headerRow.style.gap = '0.5rem';
    headerRow.style.marginBottom = '0.75rem';

    const iconWrap = document.createElement('span');
    iconWrap.style.color = 'var(--color-info)';
    iconWrap.innerHTML = icons.clock(18);

    const heading = document.createElement('h3');
    heading.textContent = 'Case Timeline & Audit Trail';
    heading.style.margin = '0';

    headerRow.append(iconWrap, heading);
    card.appendChild(headerRow);

    const stages = [
      ['Reported', incident.createdAt],
      ['Dispatched', incident.dispatchedAt],
      ['Arrived on scene', incident.arrivedAt],
      ['Redaction approved', incident.redactionApprovedAt],
      ['Blotter finalized', blotter ? blotter.finalizedAt : null],
      ['Last amended', blotter ? blotter.amendedAt : null],
    ];

    const visibleStages = stages.filter(([label, timestamp]) => (
      !(label === 'Last amended' && !timestamp)
    ));

    // Find the latest reached index for pulse effect
    let lastReachedIdx = -1;
    visibleStages.forEach(([_, ts], idx) => {
      if (ts) lastReachedIdx = idx;
    });

    const list = document.createElement('div');
    list.className = 'timeline';
    visibleStages.forEach(([label, timestamp], i) => {
      const reached = Boolean(timestamp);
      const isLatest = i === lastReachedIdx;

      const item = document.createElement('div');
      item.className = 'timeline__item';

      const rail = document.createElement('div');
      rail.className = 'timeline__rail';
      const node = document.createElement('span');
      let nodeClass = 'timeline__node';
      if (reached) {
        nodeClass += isLatest ? ' timeline__node--current' : ' timeline__node--done';
      }
      node.className = nodeClass;
      rail.appendChild(node);

      if (i < visibleStages.length - 1) {
        const connector = document.createElement('span');
        const nextReached = Boolean(visibleStages[i + 1][1]);
        connector.className = 'timeline__connector' + (reached && nextReached ? ' timeline__connector--done' : '');
        rail.appendChild(connector);
      }

      const body = document.createElement('div');
      body.className = 'timeline__body';

      const row = document.createElement('div');
      row.className = 'timeline__row';

      const name = document.createElement('span');
      name.className = 'timeline__label' + (reached ? '' : ' timeline__label--pending');
      name.textContent = label;

      const badge = document.createElement('span');
      badge.className = `timeline__status-badge ${reached ? 'timeline__status-badge--done' : 'timeline__status-badge--pending'}`;
      badge.textContent = reached ? 'Completed' : 'Pending';

      row.append(name, badge);

      const value = document.createElement('span');
      value.className = 'timeline__value';
      value.textContent = reached
        ? new Date(timestamp).toLocaleDateString('en-US', {
            month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit'
          })
        : 'Not reached yet';

      body.append(row, value);
      item.append(rail, body);
      list.appendChild(item);
    });

    card.appendChild(list);
    return card;
  }

  /**
   * §9 W7: "Admin incident resolution is shown only when the dispatch/state
   * prerequisites are met" — i.e. the incident is `dispatched` and no
   * dispatch is still active. Those are exactly the conditions the server
   * enforces (§6 PATCH /incidents/:id/status), checked here so the button
   * is never a control that would 409 on click.
   *
   * §8 forbids the mockup's invented 4-state model: the label and
   * availability come from the real `incident.status` and real dispatch
   * rows, nothing else.
   */
  function buildAdminResolvePanel() {
    const card = document.createElement('div');
    card.className = 'card';

    if (incident.status === 'resolved') {
      return buildResolvedStatusCard();
    }

    const heading = document.createElement('h3');
    heading.textContent = 'Incident resolution';
    card.appendChild(heading);

    const activeDispatch = incident.hasActiveDispatch;

    const button = document.createElement('button');
    button.className = 'primary';
    button.textContent = 'Mark incident resolved';

    let blockedBecause = null;
    if (incident.status !== 'dispatched') {
      blockedBecause = `Only a dispatched incident can be resolved — this one is ${incident.status}.`;
    } else if (activeDispatch) {
      blockedBecause = 'A dispatch is still active. Complete or cancel it before resolving.';
    }
    button.disabled = blockedBecause !== null;

    button.addEventListener('click', async () => {
      const confirmed = await confirmDialog({
        title: 'Mark this incident resolved?',
        description: 'This closes the incident. It cannot be reopened from this screen.',
        confirmLabel: 'Mark resolved',
        cancelLabel: 'Cancel',
      });
      if (!confirmed) return;

      button.disabled = true;
      button.textContent = 'Resolving…';
      try {
        await resolveIncident(incidentId);
        showToast('Incident marked resolved.', { variant: 'success' });
        await load();
      } catch (err) {
        button.disabled = false;
        button.textContent = 'Mark incident resolved';
        showToast(err instanceof ApiClientError ? err.message : 'Could not resolve the incident.', { variant: 'error' });
      }
    });

    card.appendChild(button);

    if (blockedBecause) {
      const reason = document.createElement('p');
      reason.className = 'note';
      reason.textContent = blockedBecause;
      card.appendChild(reason);
    }

    return card;
  }

  function buildReadOnlyBlotter() {
    const card = document.createElement('div');
    card.className = 'card doc-card';

    const header = document.createElement('div');
    header.className = 'doc-card__header';

    const titleGroup = document.createElement('div');
    titleGroup.className = 'doc-card__title-group';
    const heading = document.createElement('h3');
    heading.className = 'doc-card__title';
    heading.textContent = `Official Blotter Summary (Revision ${blotter.revisionNo})`;
    titleGroup.appendChild(heading);
    if (blotter.caseStatus) titleGroup.appendChild(buildCaseStatusPill(blotter.caseStatus));

    const actions = document.createElement('div');
    actions.className = 'doc-card__actions';

    const copyBtn = document.createElement('button');
    copyBtn.className = 'btn-copy';
    copyBtn.innerHTML = `${icons.fileText(14)} Copy Summary`;
    copyBtn.addEventListener('click', () => {
      navigator.clipboard.writeText(blotter.narrativeSummary);
      showToast('Blotter summary copied to clipboard.', { variant: 'success' });
    });
    actions.appendChild(copyBtn);

    header.append(titleGroup, actions);
    card.appendChild(header);

    const body = document.createElement('div');
    body.className = 'doc-blockquote doc-blockquote--blotter';
    body.textContent = blotter.narrativeSummary;
    card.appendChild(body);

    if (blotter.complainantName || blotter.respondentName || blotter.complainantContactNumber) {
      const partyNote = document.createElement('p');
      partyNote.className = 'note';
      partyNote.style.marginTop = '0.5rem';
      const parts = [];
      if (blotter.complainantName) parts.push(`Complainant: ${blotter.complainantName}`);
      if (blotter.respondentName) parts.push(`Respondent: ${blotter.respondentName}`);
      if (blotter.complainantContactNumber) parts.push(`Contact: ${blotter.complainantContactNumber}`);
      partyNote.textContent = parts.join(' · ');
      card.appendChild(partyNote);
    }

    return card;
  }

  /** The Secretary's finalize/amend panel — the point of this screen. */
  function buildBlotterPanel() {
    const card = document.createElement('div');
    card.className = 'card doc-card';

    const approved = Boolean(incident.redactionApprovedAt);
    const finalized = Boolean(blotter && blotter.finalizedAt);

    if (!approved) {
      const heading = document.createElement('h3');
      heading.className = 'doc-card__title';
      heading.textContent = 'Blotter Record Finalization';
      card.appendChild(heading);

      const note = document.createElement('p');
      note.className = 'note';
      note.style.margin = '0.5rem 0 1rem 0';
      note.textContent =
        'This incident has no approved redaction yet, so its blotter entry cannot be finalized. '
        + 'Approve the AI redaction first to comply with RA 10173 privacy regulations.';
      const link = document.createElement('button');
      link.className = 'primary';
      link.textContent = 'Go to AI Redaction Review';
      link.addEventListener('click', () => navigate('ai-review', incidentId));
      card.append(note, link);
      return card;
    }

    if (!finalized) {
      const heading = document.createElement('h3');
      heading.className = 'doc-card__title';
      heading.textContent = 'Finalize Blotter Record';
      card.appendChild(heading);
      card.appendChild(buildFinalizeForm());
      return card;
    }

    // Finalized: read-only current text plus the amendment form
    const header = document.createElement('div');
    header.className = 'doc-card__header';

    const titleGroup = document.createElement('div');
    titleGroup.className = 'doc-card__title-group';
    const heading = document.createElement('h3');
    heading.className = 'doc-card__title';
    heading.textContent = `Official Blotter Summary (Revision ${blotter.revisionNo})`;
    titleGroup.appendChild(heading);
    if (blotter.caseStatus) titleGroup.appendChild(buildCaseStatusPill(blotter.caseStatus));

    const actions = document.createElement('div');
    actions.className = 'doc-card__actions';

    const copyBtn = document.createElement('button');
    copyBtn.className = 'btn-copy';
    copyBtn.innerHTML = `${icons.fileText(14)} Copy Summary`;
    copyBtn.addEventListener('click', () => {
      navigator.clipboard.writeText(blotter.narrativeSummary);
      showToast('Blotter summary copied.', { variant: 'success' });
    });
    actions.appendChild(copyBtn);

    header.append(titleGroup, actions);
    card.appendChild(header);

    const revision = document.createElement('p');
    revision.className = 'note';
    revision.style.margin = '0.25rem 0 0.5rem 0';
    revision.textContent = `Finalized as revision ${blotter.revisionNo}. Amending creates an audited revision; previous versions are preserved in the permanent statutory register.`;

    const current = document.createElement('div');
    current.className = 'doc-blockquote doc-blockquote--blotter';
    current.textContent = blotter.narrativeSummary;

    const amendSection = document.createElement('div');
    amendSection.style.marginTop = '1.25rem';
    amendSection.style.borderTop = '1px solid var(--color-border)';
    amendSection.style.paddingTop = '1rem';

    const amendHeading = document.createElement('h4');
    amendHeading.style.margin = '0 0 0.75rem 0';
    amendHeading.style.fontSize = '0.95rem';
    amendHeading.style.color = 'var(--color-text-primary)';
    amendHeading.textContent = 'Amend Blotter Record';

    amendSection.append(amendHeading, buildAmendForm());

    card.append(revision, current, amendSection);
    return card;
  }

  function buildResolvedStatusCard() {
    const card = document.createElement('div');
    card.className = 'card resolution-badge-card';
    const resolutionDate = incident.syncedAt || incident.createdAt;
    const formattedResDate = resolutionDate
      ? new Date(resolutionDate).toLocaleDateString('en-US', {
          month: 'short', day: 'numeric', year: 'numeric', hour: '2-digit', minute: '2-digit'
        })
      : null;

    card.innerHTML = `
      <div class="resolution-badge-card__icon">${icons.checkCircle(20)}</div>
      <div style="flex:1;min-width:0;">
        <h4 class="resolution-badge-card__title">Case Closed & Resolved</h4>
        <p class="resolution-badge-card__desc">This incident was officially closed and resolved. Permanent statutory retention policies apply under Republic Act 7160 Section 394.</p>
        <div style="margin-top:0.45rem;padding-top:0.45rem;border-top:1px solid var(--color-success);display:flex;flex-direction:column;gap:0.25rem;font-size:0.75rem;color:var(--color-text-secondary);">
          ${formattedResDate ? `<span>🕒 <strong>Resolution Logged:</strong> ${formattedResDate}</span>` : ''}
          <span>🛡️ <strong>Dispatch Status:</strong> All active dispatches cleared</span>
        </div>
      </div>
    `;
    return card;
  }

  function buildLegalGuide() {
    const card = document.createElement('div');
    card.className = 'card legal-notice-card';
    card.innerHTML = `
      <div class="legal-notice-card__title">
        ${icons.shield(15)}
        <span>Katarungang Pambarangay (RA 7160)</span>
      </div>
      <p class="legal-notice-card__text">
        Under Sections 399–422 of Republic Act 7160, disputes between barangay residents are subject to mandatory Lupon conciliation before any court filing.
      </p>
    `;
    return card;
  }

  /**
   * case_status pill (migration 0009, 2026-09-05 UX pass) — displays Lupon Case status.
   */
  function buildCaseStatusPill(caseStatus) {
    const labels = {
      active: 'Lupon Case: Active',
      under_investigation: 'Lupon: Under Investigation',
      settled: 'Lupon: Settled',
      resolved: 'Lupon: Resolved'
    };
    const classes = {
      active: 'status-pill--info',
      under_investigation: 'status-pill--pending',
      settled: 'status-pill--success',
      resolved: 'status-pill--neutral'
    };
    const pill = document.createElement('span');
    pill.className = `status-pill ${classes[caseStatus] || 'status-pill--neutral'}`;
    pill.textContent = (labels[caseStatus] || caseStatus).toUpperCase();
    return pill;
  }

  function buildFinalizeForm() {
    const form = document.createElement('form');
    form.className = 'form-stack';
    form.noValidate = true;

    const label = document.createElement('label');
    label.className = 'label';
    label.htmlFor = 'blotter-finalize-summary';
    label.textContent = 'Blotter summary';

    const note = document.createElement('p');
    note.className = 'note';
    note.textContent =
      'This is the Secretary’s own record of the incident, informed by the approved redaction. '
      + 'Once finalized it cannot be overwritten — only amended, with a reason.';

    const textarea = document.createElement('textarea');
    textarea.id = 'blotter-finalize-summary';
    textarea.rows = 6;
    textarea.required = true;
    textarea.classList.add('textarea--resizable');
    // Pre-fill from the approved redaction as a starting point, since the
    // Secretary is writing a summary OF that text.
    textarea.value = incident.redactedNarrative || '';

    const { fields: partyFields, elements: partyElements } = buildPartyFields({
      complainantName: incident.complainantName,
      respondentName: incident.respondentName,
      complainantContactNumber: incident.complainantContactNumber,
    });

    const submit = document.createElement('button');
    submit.type = 'submit';
    submit.className = 'primary';
    submit.textContent = 'Finalize Blotter Record';

    form.append(label, note, textarea, ...partyElements, submit);

    form.addEventListener('submit', async (event) => {
      event.preventDefault();
      const summary = textarea.value.trim();
      if (!summary) {
        showToast('Enter a blotter summary before finalizing.', { variant: 'error' });
        return;
      }
      const confirmed = await confirmDialog({
        title: 'Finalize this blotter entry?',
        description: 'A finalized entry cannot be overwritten. Later changes require an audited amendment with a reason.',
        confirmLabel: 'Finalize',
        cancelLabel: 'Keep editing',
      });
      if (!confirmed) return;

      submit.disabled = true;
      submit.textContent = 'Finalizing…';
      try {
        await finalizeBlotter(incidentId, { narrativeSummary: summary, ...partyFields() });
        showToast('Blotter entry finalized.', { variant: 'success' });
        await load();
      } catch (err) {
        submit.disabled = false;
        submit.textContent = 'Finalize Blotter Record';
        showToast(err instanceof ApiClientError ? err.message : 'Could not finalize the entry.', { variant: 'error' });
      }
    });

    return form;
  }

  /**
   * Shared Complainant/Respondent/Contact input trio (§ migration 0008) —
   * used identically by finalize and amend. Returns a `fields()` getter
   * (reads the live input values at submit time, not at build time) and
   * the elements to append into the caller's own form.
   */
  function buildPartyFields({ complainantName, respondentName, complainantContactNumber }) {
    const complainantLabel = document.createElement('label');
    complainantLabel.className = 'label';
    complainantLabel.textContent = 'Complainant name (optional)';
    const complainantInput = document.createElement('input');
    complainantInput.type = 'text';
    complainantInput.value = complainantName || '';

    const respondentLabel = document.createElement('label');
    respondentLabel.className = 'label';
    respondentLabel.textContent = 'Respondent name (optional)';
    const respondentInput = document.createElement('input');
    respondentInput.type = 'text';
    respondentInput.value = respondentName || '';

    const contactLabel = document.createElement('label');
    contactLabel.className = 'label';
    contactLabel.textContent = 'Contact number (optional)';
    const contactInput = document.createElement('input');
    contactInput.type = 'tel';
    contactInput.value = complainantContactNumber || '';

    return {
      fields: () => ({
        complainantName: complainantInput.value.trim(),
        respondentName: respondentInput.value.trim(),
        complainantContactNumber: contactInput.value.trim(),
      }),
      elements: [complainantLabel, complainantInput, respondentLabel, respondentInput, contactLabel, contactInput],
    };
  }

  function buildAmendForm() {
    const form = document.createElement('form');
    form.className = 'form-stack';
    form.noValidate = true;

    const summaryLabel = document.createElement('label');
    summaryLabel.className = 'label';
    summaryLabel.htmlFor = 'blotter-amend-summary';
    summaryLabel.textContent = 'Amended summary';
    const summaryInput = document.createElement('textarea');
    summaryInput.id = 'blotter-amend-summary';
    summaryInput.rows = 6;
    summaryInput.required = true;
    summaryInput.classList.add('textarea--resizable');
    summaryInput.value = blotter.narrativeSummary;

    const reasonLabel = document.createElement('label');
    reasonLabel.className = 'label';
    reasonLabel.htmlFor = 'blotter-amend-reason';
    reasonLabel.textContent = 'Reason for amendment';
    const reasonInput = document.createElement('input');
    reasonInput.id = 'blotter-amend-reason';
    reasonInput.type = 'text';
    reasonInput.required = true;
    reasonInput.placeholder = 'e.g. Corrected the date of the incident';

    // case_status (migration 0009, 2026-09-05 UX pass) — forward-only,
    // matching BlotterController::amend()'s own enforcement exactly:
    // only options STRICTLY ahead of the current status are offered, and
    // 'resolved' never appears here at all — it's set only when the
    // parent incident itself is resolved (IncidentsController::
    // updateStatus()), never a Secretary's direct choice.
    const CASE_STATUS_RANK = { active: 0, under_investigation: 1, settled: 2, resolved: 3 };
    const CASE_STATUS_LABELS = { under_investigation: 'Under Investigation', settled: 'Settled' };
    const currentRank = CASE_STATUS_RANK[blotter.caseStatus] ?? 0;
    const forwardOptions = Object.keys(CASE_STATUS_LABELS).filter((key) => CASE_STATUS_RANK[key] > currentRank);

    let caseStatusSelect = null;
    let caseStatusLabel = null;
    if (forwardOptions.length > 0) {
      caseStatusLabel = document.createElement('label');
      caseStatusLabel.className = 'label';
      caseStatusLabel.htmlFor = 'blotter-amend-case-status';
      caseStatusLabel.textContent = 'Case status (optional)';
      caseStatusSelect = document.createElement('select');
      caseStatusSelect.id = 'blotter-amend-case-status';
      const keepOption = document.createElement('option');
      keepOption.value = '';
      keepOption.textContent = `Keep current (${blotter.caseStatus.replace('_', ' ')})`;
      caseStatusSelect.appendChild(keepOption);
      for (const key of forwardOptions) {
        const option = document.createElement('option');
        option.value = key;
        option.textContent = `Move to: ${CASE_STATUS_LABELS[key]}`;
        caseStatusSelect.appendChild(option);
      }
    }

    const { fields: partyFields, elements: partyElements } = buildPartyFields({
      complainantName: blotter.complainantName,
      respondentName: blotter.respondentName,
      complainantContactNumber: blotter.complainantContactNumber,
    });

    const submit = document.createElement('button');
    submit.type = 'submit';
    submit.className = 'primary';
    submit.textContent = 'Save amendment';

    form.append(summaryLabel, summaryInput, ...partyElements);
    if (caseStatusSelect) form.append(caseStatusLabel, caseStatusSelect);
    form.append(reasonLabel, reasonInput, submit);

    form.addEventListener('submit', async (event) => {
      event.preventDefault();
      const summary = summaryInput.value.trim();
      const reason = reasonInput.value.trim();
      if (!summary || !reason) {
        // The server requires both; saying so here avoids a pointless 400.
        showToast('An amendment needs both a summary and a reason.', { variant: 'error' });
        return;
      }
      const confirmed = await confirmDialog({
        title: `Amend blotter revision ${blotter.revisionNo}?`,
        description: 'This creates an audited revision. The current text is preserved and remains retrievable.',
        confirmLabel: 'Amend',
        cancelLabel: 'Cancel',
      });
      if (!confirmed) return;

      submit.disabled = true;
      submit.textContent = 'Saving…';
      try {
        await amendBlotter(incidentId, {
          narrativeSummary: summary,
          reason,
          ...partyFields(),
          caseStatus: caseStatusSelect?.value || undefined,
        });
        showToast('Amendment saved.', { variant: 'success' });
        await load();
      } catch (err) {
        submit.disabled = false;
        submit.textContent = 'Save amendment';
        showToast(err instanceof ApiClientError ? err.message : 'Could not save the amendment.', { variant: 'error' });
      }
    });

    return form;
  }
}
